### ISSUE TITLE
any example how to use Plotpartial for xgboost model in R ?

### ISSUE THREAD

**Issue by soumenms2015** [bgreenwell/pdp#103]
Hello,

I am not sure if there is any right example of applying partial or plotPartial function in case of xgboost model. I couldn't see which arguments needs to be mentioned in case of xgboost model.
Any leads in this regards would be highly appreciated.

Thanks !

**Comment by bgreenwell** [comment]
Hi @soumenms2015, thanks for posting an issue. Below is a minimal example of working with **xgboost**. For now, it's easiest to supply two arguments: `train` and `pred.fun` (at least until I update **pdp** on CRAN to reflect the newer versions of **xgboost**. Also, the approach outlined below is general enough that it can be applied to any model you can obtain predictions from, not just **xgboost**.

```r
# Load required packages
library(pdp)
library(xgboost)

# Feature matrix
X <- data.matrix(subset(boston, select = -cmedv))

set.seed(817)
bst <- xgboost(data = X, label = boston$cmedv, nrounds = 100)

# Create a prediction wrapper
pfun <- function(object, newdata) {
  p <- predict(object, newdata = newdata)
  mean(p)
}

pd <- partial(bst, pred.var = "lstat", train = X, pred.fun = pfun)

plotPartial(pd)

library(ggplot2)
autoplot(pd)
```

Additionally, you may find more information in the corresponding R Journal article: https://journal.r-project.org/archive/2017/RJ-2017-016/index.html.

**Comment by soumenms2015** [comment]
Thanks a lot and it works perfectly.
