### ISSUE TITLE
Options to modify palettes

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [bgreenwell/pdp#116]
Hi, A small suggestion: 
to give the possibility to adjust the palette used for the pdps in partial().
For instance: direction, begin and end.
Thks,
Jérôme

**Comment by bgreenwell** [comment]
Hi @JeromeMathieuEcology, sorry for the long delay in response, but you can already do that. Here's a minimal example using both plotting functions:
```r
library(pdp)
library(ggplot2)
library(ranger)

rfo <- ranger(cmedv ~ ., data = boston)

pd <- partial(rfo, pred.var = c("rm", "lstat"), chull = TRUE)

pal1 <- viridisLite::inferno(100, alpha = 1, begin = 0, end = 0.3)
pal2 <- viridisLite::inferno(100, alpha = 1, begin = 0.3, end = 0.9)

gridExtra::grid.arrange(
  plotPartial(pd, col.region = pal1),
  plotPartial(pd, col.region = pal2),
  autoplot(pd, palette = "inferno", begin = 0, end = 0.3),
  autoplot(pd, palette = "inferno", begin = 0.3, end = 0.9),
  nrow = 2
)
```
![image](https://user-images.githubusercontent.com/3777755/124607394-cc7b4700-de3b-11eb-9c25-dec565c1e6cf.png)
