### ISSUE TITLE
Implement Friedman & Popescu's H-statistic?

### ISSUE THREAD

**Issue by bgreenwell** [bgreenwell/pdp#12]
This is a statistic for assessing the strength of interaction between predictors and is based on the partial dependence functions. Start with `gbm`'s implementation; see `?gbm::interact.gbm`.

**Comment by bgreenwell** [comment]
If our method in the [`vip`](https://github.com/AFIT-R/vip-manuscript) package works out, we can just use that instead.

**Comment by Weekend-Warrior** [comment]
Any update on this? Thanks!

**Comment by bgreenwell** [comment]
Well, we could always add an H-statistic function, but it would likely be slow. Would you find this useful? If so, a colleague of mine has written some code which I could try and pull into this package. You might also try experimenting with the `vint()` function---similar in spirit to the H-statistic---from the `vip` package (though, it is experimental at this stage).

**Comment by Weekend-Warrior** [comment]
It would be very convenient, if it's not too much trouble.

**Comment by bgreenwell** [comment]
Out of scope. Perhaps this belongs in its own package?
