### ISSUE TITLE
inv.link argument ignored for binomial GLMs

### ISSUE THREAD

**Issue by RoelVerbelen** [bgreenwell/pdp#125]
Hi @bgreenwell,

Thanks for the great package!

The `inv.link` argument is very handy for transforming predictions back to the right scale prior to summarizing, but unfortunately it gets ignored for logistic regression models where the specifyc `prob` argument is to be used instead. 

Could the code be changed to allow for a consistent use of the  `inv.link` argument (as alternative to `prob`)?

``` r
library(pdp)

# Define boolean outcome
iris$class <- iris$Species == "virginica"

# Logistic regression
model <- glm(class ~ Sepal.Length, data = iris, family = binomial(link = "logit"))

# PD on linear predictor scale
partial(model, 
        pred.var = "Sepal.Length",
        grid.resolution = 5)
#>   Sepal.Length       yhat
#> 1          4.3 -2.5869756
#> 2          5.2 -1.4205492
#> 3          6.1 -0.2541227
#> 4          7.0  0.9123038
#> 5          7.9  2.0787302

# FAILS: inv.link ignored
partial(model, 
        pred.var = "Sepal.Length", 
        grid.resolution = 5,
        inv.link = plogis)
#>   Sepal.Length       yhat
#> 1          4.3 -2.5869756
#> 2          5.2 -1.4205492
#> 3          6.1 -0.2541227
#> 4          7.0  0.9123038
#> 5          7.9  2.0787302

# Transforming requires a separate argument to be used
partial(model, 
        pred.var = "Sepal.Length", 
        grid.resolution = 5, 
        prob = TRUE)
#>   Sepal.Length        yhat
#> 1          4.3 0.005630273
#> 2          5.2 0.055143285
#> 3          6.1 0.375604935
#> 4          7.0 0.861118073
#> 5          7.9 0.984593819
```

<sup>Created on 2022-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by brandongreenwell-8451** [comment]
Hi @RoelVerbelen, thanks for dropping a note. In short, yes it could be changed, but the easier solution would be to override `partial()`'s default behavior for binomial GLMs. In short, `partial()` will assume classification/probability estimation for GLMs with a binomial family, which doesn't support `inv.link` because it's assumed you likely want probabilities. The `inv.link` options only supports regression problems (logistic regression is a mix of both). If you override the default by setting `type = 'regression'` in the call to `partial()`, it'll treat it as regression and ensure the output is on the original logit scale, which you can then transform to probabilities using the `inv.link` argument:

```r
partial(model, 
        pred.var = "Sepal.Length", 
        grid.resolution = 5,
        type = "regression",  # <- just add this line
        inv.link = plogis)
#>    Sepal.Length        yhat
#>1                   4.3 0.005630273
#>2                   5.2 0.055143285
#>3                   6.1 0.375604935
#>4                  7.0 0.861118073
#>5                  7.9 0.984593819
```
Is that a viable solution for your workflow?

**Comment by RoelVerbelen** [comment]
Thank you for your quick reply! 

Using `type = "regression"` is a viable solution for me as the output is also more in line with my expectation: the output on the logit scale using `type = "classification"` is a factor 2 smaller than I anticipated.

``` r
# PD on linear predictor scale
partial(model, 
        pred.var = "Sepal.Length", 
        grid.resolution = 5,
        type = "regression")
#>   Sepal.Length       yhat
#> 1          4.3 -5.1739512
#> 2          5.2 -2.8410983
#> 3          6.1 -0.5082454
#> 4          7.0  1.8246075
#> 5          7.9  4.1574604

# PD on linear predictor scale (divided by a factor of 2)
partial(model, 
        pred.var = "Sepal.Length",
        grid.resolution = 5)
#>   Sepal.Length       yhat
#> 1          4.3 -2.5869756
#> 2          5.2 -1.4205492
#> 3          6.1 -0.2541227
#> 4          7.0  0.9123038
#> 5          7.9  2.0787302
```

Thanks for the help!

**Comment by bgreenwell** [comment]
For classification models, all non probability output is on a “centered logit” scale as described in the packages R journal article. The reason is mostly for consistency between binary and multi nominal outcomes.
