### ISSUE TITLE
pdp: new gbm release

### ISSUE THREAD

**Issue by pdmetcalfe** [bgreenwell/pdp#15]
Hi!

We're coming up to a new release of gbm which considerably tidies the code and introduces a much stricter NAMESPACE.  We've also removed the multinomial distribution, which was essentially unsupported and rather buggy code, and it looks like it's breaking your package.

Would it be possible for you to take a look?

[00check.log.txt](https://github.com/bgreenwell/pdp/files/528897/00check.log.txt)

**Comment by bgreenwell** [comment]
Thanks for the heads up! Should be an easy fix. Any plans to add back multinomial support in the future?

**Comment by pdmetcalfe** [comment]
If someone volunteers to stay around and look after it!

[it shouldn't be too hard to put back in, if only as lots of Bernoulli classification problems...]

**Comment by bgreenwell** [comment]
Closing this and opening up a separate issue regarding support for the new gbm3.
