### ISSUE TITLE
Add quantiles and trim.outliers options to partial?

### ISSUE THREAD

**Issue by bgreenwell** [bgreenwell/pdp#24]
Example usage:
```r
partial(obj, pred.var = "x", quantiles = TRUE, probs = 1:9/10, plot = TRUE))
partial(obj, pred.var = "x", trim.outliers = TRUE, plot = TRUE))
```

**Comment by bgreenwell** [comment]
```{r}
predGrid.default <- function(object, pred.var, train, grid.resolution = NULL,
                             quantiles = FALSE, probs = 1:9/10) {
  pred.val <- lapply(pred.var, function(x) {
    if (is.factor(train[[x]])) {
      levels(train[[x]])
    } else {
      if (!is.null(grid.resolution) && quantiles) {
        stop("Can only specify one of grid.resolution or quantiles, but not both.")
      }
      if (quantiles) {
        quantile(train[[x]], probs = probs, na.rm = TRUE, names = FALSE)
      } else {
        if (is.null(grid.resolution)) {
          grid.resolution <- min(length(unique(train[[x]])), 51)
        }
        seq(from = min(train[[x]], na.rm = TRUE),
            to = max(train[[x]], na.rm = TRUE),
            length = grid.resolution)
      }
    }
  })
  pred.grid <- expand.grid(pred.val)
  names(pred.grid) <- pred.var
  pred.grid
}
```

**Comment by DeFilippis** [comment]
If I want to specify my own outlier treatment strategy, or simply exclude the 99th percentile of observations, how would I go about doing that?

**Comment by DeFilippis** [comment]
How can I add my own custom outlier function?  I attempted to do something like this:

limit_outliers <- function(data, column, cut_point) {
  max_value = quantile(data[, column], cut_point, na.rm = T)
  pred = data[, column]
  pred_df = as.data.frame(pred[which(pred <= max_value)])
  names(pred_df) = column
  return(pred_df)
}

And then feed in this function a dataframe returned by this function into `pred.grid`, but the pdp function wouldn't even begin (no progress on progress bar).

**Comment by bgreenwell** [comment]
Hi @DeFilippis the default for numeric features is the minimum between 51 and the number of unique feature values.

**Comment by bgreenwell** [comment]
You can also control extreme observations using the `quantiles = TRUE` and `probs = seq(from = 0.01, to = 0.99, by = 0.02)` arguments, for example; the latter would exclude anything beyond the 1-st and 99-th percentiles.

**Comment by DeFilippis** [comment]
@bgreenwell Thanks a bunch!  I couldn't quite understand how to use probs from the documentation, but that is way easier than my custom function!  Thanks.
