### ISSUE TITLE
xgboost using xbg.DMatrix

### ISSUE THREAD

**Issue by dkincaid** [bgreenwell/pdp#34]
I'm trying to use pdp with an xgboost model. The training data is mostly text that I am encoding using bag of words. So I start off with a data frame that contains a column of text. That text is tokenized and a sparse term document matrix created. This matrix is what is used to train the xgboost model.

It appears that pdp can't handle this situation yet where the training data for the xgboost model isn't in a data frame, but in a matrix. I tried this:

```R
partial(xgb_fit, train = train_matrix, pred.var = "price")
Error in partial.default(xgb_fit, train = train_matrix, pred.var = "price") : 
  price not found in the training data.
```

but as you can see it doesn't work. Here `train_matrix` is a xgb.DMatrix object that was created from the bag of words term-document matrix of type dgCMatrix.

Is it possible to use pdp to generate partial dependence plots in this case?

**Comment by bgreenwell** [comment]
Yes, it is possible to use `pdp` with `"xgb.Booster"` objects fit using training data that iherits from class`"xgb.DMatrix"`. For now, you still need to supply the `train` argument in the call to `pdp` with a data frame (without the response). Here is a small example:

```r
# Load required packages
library(pdp)
library(xgboost)

# Load the data
data(pima)
X <- subset(pima, select = -diabetes)
y <- ifelse(pima$diabetes == "pos", 1, 0)

# Parameters for XGBoost model
param.list <- list(max_depth = 5, eta = 0.01, objective = "binary:logistic", 
                   eval_metric = "auc")

# Fit an XGBoost model
set.seed(101)
pima.xgb <- xgb.train(params = param.list, 
                      data = xgb.DMatrix(data.matrix(X), label = y), 
                      nrounds = 500)

# Partial of diabetes test result on glucoe
partial(pima.xgb, pred.var = "glucose", plot = TRUE, train = X)
```

Hopefully soon I can add direct support for matrices, etc. But for now, the `pdp` option `train` requires a data frame. Please let me know if this works or if you have any other questions. Also, I have a manuscript that should appear in the next issue of The R Journal with more details; I'd be happy to supply you with a preprint if that would help.

**Comment by dkincaid** [comment]
Thanks. I was looking at the manuscript. The problem I have is that the data frame that the data is has a column, let's call it "description", that is a 5 or 6 word product description. This values in this description column get tokenized and put into a document-term matrix (the row corresponds to the row in the data frame, but the columns of the matrix are the vocabulary words across all descriptions and then the value in the matrix cell i,i is the number of times token j appears in description i. This matrix is the training data given to xgboost.

So the problem is that the feature names (the tokens) are not columns in the data.frame. The feature names are in the matrix. If that's not clear I can put together a small example that demonstrates it.

**Comment by bgreenwell** [comment]
If you wouldn't mind putting together a small example, that would help.

**Comment by bgreenwell** [comment]
But I do think I see what you are saying. `partial` should work if you give supply the `train` argument with a data frame version of your matrix (not the original training data that you created a bag of words from), with column names for each word.

**Comment by dkincaid** [comment]
Here is the example: https://gist.github.com/dkincaid/87f0fbeb912cf23816c340b4fbe30baa

Hopefully it only includes one package that you may not have installed already - text2vec.

Part of the problem with your suggestion of turning the matrix into a data frame is that it is too big. At least that was the error I was getting when I tried to do that. I may fiddle with that a little bit more.

**Comment by bgreenwell** [comment]
This worked for me (took about 1.5 minutes on a five year old laptop):

```r
dtm_train_df <- as.data.frame(as.matrix(dtm_train))  # convert to matrix, then data frame
pd.bad <- partial(xgb_fit, train = dtm_train_df, pred.var = "bad", progress = "text")
plotPartial(pd.bad) 
```

Note, however, that the line might be flat due to low iteration numbers. I had to bump `nrounds` to 100 before I saw anything interesting. I'll start working this weekend on allowing matrices (including spare matrices). Let me know if you still have issues.

**Comment by dkincaid** [comment]
Thanks! Good to know that works for smaller data sizes. I can use it on a couple of my smaller models. The larger ones still won't convert into data frames. If there is anything I can do to help, please let me know.

**Comment by bgreenwell** [comment]
Contributions are always welcome, especially if it improves support for XGBoost models! :)

**Comment by bgreenwell** [comment]
The `train` argument in `partial` now accepts objects of class `"matrix"` or `"dgCMatrix"`; possibly more later.

**Comment by dkincaid** [comment]
Excellent! Thank you! I just tried it out and it works great! A little bit slow, but not intolerable. Have you looked into how you could use the weighted tree algorithm with xgboost like you are for GBM? I have no idea if it's even possible. Thanks for making this enhancement so quickly!

**Comment by dkincaid** [comment]
Regarding the xgb.DMatrix, I wouldn't worry about that. It seems like that will be constructed from one of the other types that you are supporting anyway, so shouldn't be an issue.
