### ISSUE TITLE
Error in FUN(X[[i]], ...) :    only defined on a data frame with all numeric variables > 

### ISSUE THREAD

**Issue by makonkey** [bgreenwell/pdp#55]
I have been trying pdp with the Titanic dataset.  I keep getting the above error.  I have got it to work with other dataset with categorical data. In my version of the Titanic all varaibles are character variables.  I am just building a tree with rpart.  I probably am doing something very stupid.  Apologies if I am.

**Comment by bgreenwell** [comment]
It's difficult to determine what the issue is without a reproducible example. Could you kindly provide the code you are using? If so, I can take a closer look.

**Comment by makonkey** [comment]
Brandon

I really appreciate your quick reply.  I strongly suspect I am doing something very stupid.  I enclose the dataset I used and obviously the read.csv accesses it on my computer.

TITANIC <- read_csv()
library(rpart)
library(pdp)
fit2<-rpart(data=TITANIC, Survived~.)   # very much a basic tree
par<-partial(fit2,pred.var="Gender",training=TITANIC)


Very simple example.  I loved your examples in the paper which I am using.

Many thanks

Myra

**Comment by makonkey** [comment]
Brandon

Thought I sent the data to you.  Losing my mind today!!!

Thanks

Myra

**Comment by bgreenwell** [comment]
Nope, haven't received any data, or a link to where to download it.

**Comment by makonkey** [comment]
Brandon

I attached the data to the email - an excel file

All the best

Myra

Sent from my iPad

On 12 Oct 2017, at 17:52, Brandon Greenwell <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope, haven't received any data, or a link to where to download it.

**Comment by bgreenwell** [comment]
I haven't received any e-mail with an attachment.

**Comment by makonkey** [comment]
Brandon

I definitely emailed  you at this address with an attachment.  Can I put the file somewhere?

Sorry about this

Myra

**Comment by bgreenwell** [comment]
Must not have come through. In any case, you should just be able to drag and drop the file in the comment box. Otherwise, you can send it to my email which can be found here: https://cran.r-project.org/web/packages/pdp/index.html.

**Comment by bgreenwell** [comment]
@makonkey, were you ever able to figure out the issue?

**Comment by makonkey** [comment]
Brandon

Thank you for getting back to me.  I have to be honest.  I cannot even remember what the problem was.  Hard semester.  I did have a problem recently which I traced back to how Rstudio was reading in data.  It was reading data into a tibble type frame.  Some packages will work with this structure but some will not.  PDP was one of these packages.  It ran fine with Random forests but pdp did not like the tibble structure.  I have a funny feeling this was the same problem.  Only found the answer by complete chance.

I apologise for not getting back to you. All you have to do is convert the structure using as.data.frame

Hope this helps

Thank you

Myra

**Comment by bgreenwell** [comment]
No problem, thanks for the speedy reply! I'll open a separate issue to handle `tibble`s.

**Comment by makonkey** [comment]
Brandon

Does this makes sense to you?

Myra

**Comment by bgreenwell** [comment]
Yes, I just tested out myself actually. I'll push a fix in the next week or so.
