### ISSUE TITLE
How to use this for models created by H2o?

### ISSUE THREAD

**Issue by deepakagrawal** [bgreenwell/pdp#61]
Can I have a simple workaround to make PDP run with models trained with H2o?

**Comment by bgreenwell** [comment]
Certainly, but be warned that this can be slow with large models and data sets. Also, `h2o` has a built-in function `h2o.partialPlot()`. If you have an `h2o` model, you can use the foloowing:

```r
pfun <- function(object, newdata) {
  nd <- as.h2o(newdata)
  mean(h2o.predict(object, newdata = nd))
}
pd <- partial(<model name>, pred.var = "x", train = <data frame>, 
                       pred.fun = pfun, progress = "text")
```

**Comment by pelayoarbues** [comment]
Using this approach with a model trained in h2o (v 3.20.0.2) I got the following error: 

Error: is.function(...f) is not TRUE
