### ISSUE TITLE
Allow returning intermediate results

### ISSUE THREAD

**Issue by mstaniak** [bgreenwell/pdp#78]
I would like to use intermediate results for example for calculating pointwise standard deviations, can you please such an option to partial()?
I know it might be problematic because partial() returns a data frame with final values, but I hope there is a way to do it.

**Comment by mstaniak** [comment]
Thanks for the explanation, this is exactly what I was looking for

**Comment by bgreenwell** [comment]
Awesome. If it makes it easier to still add this feature in the future (i.e., `partial(..., se = TRUE, ...)`), let me know and I'll add it to the TODO list. But honestly, using the `pred.fun` argument gives you the flexibility to do anything you want.
