### ISSUE TITLE
Error: Objects of type purrr_function_partial/function not supported by autoplot.

### ISSUE THREAD

**Issue by sgadavi3** [bgreenwell/pdp#87]
I get the error 'Error: Objects of type purrr_function_partial/function not supported by autoplot.' when running: 

`p2 <- partial(model, pred.var = "rm", pred.fun = pred_wrapper, train = as.data.frame(train_x)) %>%
  autoplot(alpha = 0.1)`

based on the example https://bgreenwell.github.io/pdp/articles/pdp-example-tensorflow.html

**Comment by bgreenwell** [comment]
@sgadavi3 You must have __purrr__ loaded; `pdp::partial()` conflicts with `purrr::partial()`. You can either try to detach __purrr__ 
```r
detach("package:purrr", unload = TRUE)
```
or use 
```r
p2 <- pdp::partial(model, pred.var = "rm", pred.fun = pred_wrapper, train = as.data.frame(train_x)) %>% autoplot(alpha = 0.1)
```
Let me know which, if either, works!

**Comment by sgadavi3** [comment]
@bgreenwell Sorted by closing R and reseting Mac!
