### ISSUE TITLE
Trellis object generation even with plot.engine = ggplot

### ISSUE THREAD

**Issue by DeFilippis** [bgreenwell/pdp#94]
I am trying to construct a ggplot2 object with the following specifications:

```
pdp  <- partial(cforest, 
                       pred.var = "x1", 
                       plot = TRUE, rug = TRUE, trim.outlier = TRUE, 
                       parallel = TRUE, paropts = list(.packages = "ranger"),
                       plot.engine = "ggplot2")
```

However, doing so will automatically produce a plot in the lattice framework, and I don't know how to force it to use ggplot2. 

I have tried turning the plotting environment off, and then manually constructing the graph like so:

```
ggplot(data = pdp, aes(x = x1, y = yhat)) +
  geom_line() +
  theme_light() +
  ggtitle("ggplot2-based PDP") +
  geom_rug(sides="b", color = "blue") 
```

Which has the problem of not being able to import the correct "geom_rug" data that is calculated internally.  

What am I doing wrong?

**Comment by DeFilippis** [comment]
Follow-up on this: The solution appears to be that turning `plot = TRUE`, automatically defaults to the lattice framework.  You can force ggplot by doing `plot = FALSE` and manually plotting using ggplot framework. 

I still haven't figured out how to get rug data from the data.frame produced when you set `plot = FALSE`, however.

**Comment by bgreenwell** [comment]
Yep, the default is to use **lattice**, but `plot.engine = "ggplot2"` should do what it's supposed to do? Can you post a complete reproducible example that I can run on my end to see what's happening?

**Comment by bgreenwell** [comment]
Does this only occur when using `parallel = TRUE`?

**Comment by DeFilippis** [comment]
It occurs regardless of whether or not I use `parallel = TRUE`

Reproducible example:

```

data(mtcars)
fit_rg <- ranger(
  formula = mpg ~ ., 
  data = mtcars,
)

pdp  <- partial(fit_rg, 
                pred.var = "cyl", 
                plot = TRUE, rug = TRUE, trim.outlier = TRUE, 
                plot.engine = "ggplot2")

pdp
```

**Comment by DeFilippis** [comment]
I'm still getting a lattice object even with:

```pdp  <- partial(fit_rg, 
                pred.var = "cyl",
                plot.engine = "ggplot2",
                plot = TRUE, 
             )```

**Comment by bgreenwell** [comment]
Strange, I get a **ggplot2** plot:

![image](https://user-images.githubusercontent.com/3777755/61641001-4eccc980-ac6c-11e9-8372-dee565f327fe.png)

**Comment by bgreenwell** [comment]
Hey @DeFilippis I have yet to be able to reproduce this issue. Please reopen if you run into it again.
