### ISSUE TITLE
Feature Request: Accumulated Local Effect Plots

### ISSUE THREAD

**Issue by DeFilippis** [bgreenwell/pdp#95]
I think it might be nice for the `pdp` package to have have an option to generate accumulated local effect plots (ALE) plots.  See Apley (2007): https://arxiv.org/pdf/1612.08468.pdf.  Many of my predictors are correlated with one another, so I'm weary on how much weight to give to PDPs.  

As far as I know, ALE plots are implemented in the `iml` library, the `ALEplot` library and `DALEX`.  I much prefer the syntax of your `pdp` library, however, and conceptually they're fairly easy to understand.

**Comment by bgreenwell** [comment]
Hi @DeFilippis sorry for the delayed response. Unfortunately, ALE plots are beyond the scope of **pdp**, which is only meant to produce PDPs and their byproduct ICE/c-ICE curves. If you are concerned with high correlation, then the [`squash()` function trick](https://github.com/bgreenwell/pdp/issues/91) to producing marginal effect plots can be useful.

**Comment by DeFilippis** [comment]
No worries!  Thanks.
