### ISSUE TITLE
Feature Request: 95% confidence intervals around a PDP?

### ISSUE THREAD

**Issue by DeFilippis** [bgreenwell/pdp#96]
I'm wondering if it's possible to get 95% confidence bands around the predictions in a PDP plot using this library?

It looks like this is possible using `parDepPlot`implement: https://github.com/cran/interpretR/blob/master/R/parDepPlot.R

**Comment by bgreenwell** [comment]
Yes it is, but I hesitate calling them confidence bands. Nonetheless I wrote a small article on how to accomplish this here: https://bgreenwell.github.io/pdp/articles/pdp-se.Rmd.html. Let me know if you have any questions!

**Comment by DeFilippis** [comment]
This is great!  Thanks for this.  Do you know if there is anyway to get more standard confidence bands -- perhaps with bootstrapped' standard errors?  

I'm not exactly sure how this package implements it, but it looks like they have something like this: https://cornelllabofornithology.github.io/ebirdst/reference/plot_pds.html

**Comment by bgreenwell** [comment]
I don't unfortunately, nor have I seen any literature that supports this. I would argue that PDPs arise from grouped data (think about each ICE curve as a group), and so traditional confidence interval procedures don't seem like the right approach here. Would be interesting to see any work in this area.

**Comment by kaplarac** [comment]
Thanks for this fantastic package! 

I need to compute some type of confidence interval/standard error for my partial dependence plots, and would love to follow procedures in the article mentioned on August 6, 2019 at this link: https://bgreenwell.github.io/pdp/articles/pdp-se.Rmd.html. However, the link is no longer live -- could you help me access this content?

Thank you!

**Comment by bgreenwell** [comment]
Hi @kaplarac I’m not at a computer at the moment so I can’t post an example, but it’s pretty easy to obtain standard errors. PDPs are just averaged predictions so only a light modification to the prediction function is necessary. 

For now, here’s a link to the old markdown file that had the example I think you’re alluding to: 

https://github.com/bgreenwell/pdp/blob/68c3cd1af4a474e28b2e96e1695112bc4b7d63af/vignettes/pdp-se.Rmd

**Comment by bgreenwell** [comment]
Also, while the standard error computation is legit, I would caution calling anything a confidence interval here for several reasons!

**Comment by kaplarac** [comment]
Thanks so much @bgreenwell! The standard error code worked great, and I'll be careful with my language around it. I've been trying to understand uncertainty estimation around pdps. Is the term "confidence interval" inappropriate here because prediction variability isn't inherently estimated through the modeling process (e.g. with Random Forest)? Really appreciate your help!
